### ISSUE TITLE
[DataTable]: First column overlaps second column

### ISSUE THREAD

**Issue by oleksapro** [epam/UUI#1163]
## Description

In DataTable if you resize first column to the width which will be less than content, the content starts overlaping second column due to styles from class `.content-wrapper`.

```scss
// uui-components\src\table\DataTableCell.scss
.content-wrapper {
    display: flex;
    flex-grow: 1;
}
```

## Actual result

![image_2023_03_28T16_13_07_912Z](https://user-images.githubusercontent.com/7101211/228309106-f09b659a-f4f0-4fdb-ab1c-caa0a2459d74.png)

https://codesandbox.io/s/uui-table-first-column-olto9o?file=/Example.tsx

## Environment

* UUI version: 4.10.2
* Browser name: Google Chrome
* Operating System: Windows
